import { z } from 'zod';
import {
	address,
	barangay,
	bir,
	city,
	companyDescription,
	companyName,
	companyType,
	composition,
	condition,
	email,
	employeeCount,
	firstName,
	hasLending,
	industry,
	isAuthorizedSignatory,
	lastName,
	maritalStatus,
	middleName,
	mobile,
	model,
	nationality,
	ownership,
	position,
	province,
	registrationDate,
	shareholderType,
	subIndustry,
	title,
	hasVotingPower,
	website,
	employmentHistorySchema,
	companyId
} from './shape-properties';

export const companyInfoFormSchema = z.object({
	id: z.number().optional(),
	companyType,
	companyName,
	companyDescription,
	website,
	email,
	mobile,
	bir,
	hasLending,
	registrationDate,
	employeeCount,
	industry,
	subIndustry,
	composition,
	condition,
	model,
	address,
	province,
	city,
	barangay
});

export const indShareholderFormSchema = z.object({
	id: z.number().optional(),
	companyId,
	title,
	shareholderType,
	firstName,
	lastName,
	middleName,
	position,
	ownership,
	nationality,
	maritalStatus,
	mobile,
	email,
	hasVotingPower,
	isAuthorizedSignatory,
	employmentHistory: z.array(employmentHistorySchema).optional()
});

export const compShareholderFormSchema = z.object({
	id: z.number().optional(),
	companyId,
	companyName,
	companyWebsite: website,
	shareholderType,
	ownership,
	nationality,
	mobile,
	email,
	hasVotingPower,
	isAuthorizedSignatory,
});
